sudo: false
language: python
python:
    - '2.7'
    - '3.3'
    - '3.4'
    - '3.5'
install:
    - pip install -r requirements.txt
    - pip install coverage coveralls pytest
script:
    - coverage run --source=myql -m pytest -v tests/tests.py
env:
  global:
    secure: hXpkZqclyUXMX586jS4BtJmYsrszVr/jWbMiLWLOZ2z7n5LK9INziKkOqYu0JTBskAHVEmhxJ7oNOD9gI/06btLO5NLBONN3qtsHq4UruCo0Zlx2BgaDfR5FqnrVqk+fMbLCbzWgo0wShM4o8jTGy7l22xqhhYAsuubmayqEfPk=
before_install:
- openssl aes-256-cbc -K $encrypted_60f42691f4f2_key -iv $encrypted_60f42691f4f2_iv
  -in credentials.json.enc -out credentials.json -d
after_success:
    - coverage report -m
    - coveralls
